### ISSUE TITLE
00-install-iRODS4.md, "Create admin user" section, user renaming documentation

### ISSUE THREAD

**Issue by juanlufont** [EUDAT-Training/B2SAFE-B2STAGE-Training#34]
Maybe the documentation about how to rename an already existing user should be left out of the scope of the documentation. It is an "advanced hack" and it could have some side effects (applications that are already using a configuration that includes the original user name).

Should this section to be removed?

**Comment by chStaiger** [comment]
Many thanks for the hint. 
The section is removed.
