### ISSUE TITLE
develop working with curl and handle v8

### ISSUE THREAD

**Issue by cookie33** [EUDAT-Training/B2SAFE-B2STAGE-Training#37]
The development curl states:
### We will register a public file from figshare.

We are going to create a new PID by using the PUT request.
The request method is -X PUT followed by the actual json data 

``` sh
-X PUT --data '{"values":[ \
    { \
        "index":100,\
        "type":"HS_ADMIN",\
        "data":{\
            "value":{\
                "index":200,\
                "handle":"0.NA/1000",\
                "permissions":"011111110011",\
                "format":"admin"\
            },\
            "format":"admin"\
        }\
    },\
    {\
        "index":1,\
        "type":"URL",\
        "data":"www.google.com"\
    }
]
}'
```

This seems incorrect. It has to be something like:

``` sh
-X PUT --data '{"values": [{
        "index": 1,
        "type": "URL",
        "data": {
            "format": "string",
            "value": "www.test1.com"
        }
    }, {
        "index": 100,
        "type": "HS_ADMIN",
        "data": {
            "format": "admin",
            "value": {
                "handle": "0.NA/1000",
                "index": 200,
                "permissions": "011111110011"
            }
        }
    }]
}'
```

or in normal strings:

``` sh
 -X PUT --data   '{"values": [ { "index": 1, "type": "URL","data": {"format": "string","value": "www.test1.com"}}, { "index": 100,"type": "HS_ADMIN","data": {"format": "admin","value": {"handle": "0.NA/1000","index": 200,"permissions": "011111110011"}}} ]}'
```

It seems there has been used a short abbreviation and not everywhere the format "string" is used in this development branch for URL and other types.

**Comment by chStaiger** [comment]
Many thanks. I corrected it.

**Comment by cookie33** [comment]
Hi,

The code does not show it has been changed.

Greetings,

**Comment by chStaiger** [comment]
I removed the '\'s in the string. They were wrong.
The rest is like you indicated, BUT, I use a different order of the items in the dictionary I post. Since it is a dictionary, the order does not seem to play a role.
I do not use the key 'format' when defining the data at index 1. But it also does not seem to hinder the creation of a PID.
