### ISSUE TITLE
mention in CURL documentation that type is always in capitals

### ISSUE THREAD

**Issue by cookie33** [EUDAT-Training/B2SAFE-B2STAGE-Training#54]
The page https://github.com/EUDAT-Training/B2SAFE-B2STAGE-Training/blob/master/07a-Working-with-PIDs_CURL.md shows examples how to create handles using curl.

Please add a note which states that the type. for instance: `URL`, `HS_ADMIN` etc should always be in capitals.

**Comment by chStaiger** [comment]
Done!
